### ISSUE TITLE
Postcss @apply error. After last Nuxt update not all styles are applied using @apply.

### ISSUE THREAD

**Issue by MichaelGitArt** [windicss/nuxt-windicss#164]
After one of the last updates of nuxt 3, windicss '@apply' rule doesn't work properly. Paddings, margins,  flex styles

**Steps to reproduce the behavior:**
1. Clone repository [https://github.com/MichaelGitArt/nuxt-windicss-issue](https://github.com/MichaelGitArt/nuxt-windicss-issue)
2. Run npm install and npm run dev
3. See error:

With '@apply' rule it doesn't work well. Not all rules are applied. **Padding, margins, flex rules**

<img width="341" alt="image" src="https://user-images.githubusercontent.com/34610289/156441702-cc0ab1a5-b71a-4ec5-b6e2-2f2b75da557e.png">

Below you can see how it should work (it's with windicss classes): 
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/34610289/156441832-4999c9eb-e05f-48d0-9d65-1a8ed6a372c5.png">

**Comment by kadiryazici** [comment]
encountered this problem too

**Comment by alvarosabu** [comment]
Yep, similar issue here ![Screenshot 2022-03-10 at 13 32 19](https://user-images.githubusercontent.com/4699008/157662467-3d6744c9-5940-435a-9191-8c9e74a73d16.png)

**Comment by MichaelGitArt** [comment]
No any updates? :(

**Comment by T-Zahil** [comment]
Same issue here 👋

**Comment by harlan-zw** [comment]
Hey guys, sorry about the lack of communication on this issue.

This problem is related to Nuxt 3 switching to Vite. When using Vite the `vite-plugin-windicss` will be used. The vite plugin does not support @apply in `scss` and it's not something that I maintain (I do the webpack integration and this module).

The solution will likely come with the v4 of windi. Until then I'd suggest only using `@apply` in plain CSS blocks

**Comment by harlan-zw** [comment]
Actually I completed overlooked a configuration that the Vite plugin explicitly uses.. Thanks for bringing that to my attention @replygirl, issue is resolved in 2.3.1
